backend:
      name: git-gateway 
      branch: main
media_folder: "/public/images/uploads" # Location where files will be stored in the repo
public_folder: "/images/uploads"
collections:
  #- name: "companyInformation" # Used in routes, e.g., /admin/collections/blog
    #label: "Ingresar datos de la compañía" # Used in the UI
    #folder: "src/content/docs/companyInformation" # The path to the folder where the documents are stored
    #create: true # Allow users to create new documents in this collection
    #fields: # The fields for each document, usually in frontmatter
      #- { label: "Layout", name: "layout", widget: "hidden" }
      #- { label: "Title", name: "title", widget: "string" }
      #- { label: "Publish Date", name: "date", widget: "datetime" }
      #- { label: "Featured Image", name: "thumbnail", widget: "image" }
      #- { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      #- { label: "Body", name: "body", widget: "markdown" }

  - name: "login" 
    label: "Inicio de sesión" 
    folder: "src/content/docs/login" 
    create: true 
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "navegacion"
        name: "sidebar"
        widget: "object"
        fields: 
          - { label: "Orden", name: "order", widget: "number", default: 1 }
  
  - name: "concepts" 
    label: "Conceptos" 
    folder: "src/content/docs/concepts" 
    create: true 
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "navegacion"
        name: "sidebar"
        widget: "object"
        fields: 
          - { label: "Orden", name: "order", widget: "number", default: 1 }
    
  - name: "transmission" 
    label: "Transmision" 
    folder: "src/content/docs/transmission" 
    create: true 
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "navegacion"
        name: "sidebar"
        widget: "object"
        fields: 
          - { label: "Orden", name: "order", widget: "number", default: 1 }
  
  - name: "transmissionConsultation" 
    label: "Consulta de Transmisiones" 
    folder: "src/content/docs/transmissionConsultation" 
    create: true 
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "navegacion"
        name: "sidebar"
        widget: "object"
        fields: 
          - { label: "Orden", name: "order", widget: "number", default: 1 }
  
  - name: "users" 
    label: "Usuarios" 
    folder: "src/content/docs/users" 
    create: true 
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "navegacion"
        name: "sidebar"
        widget: "object"
        fields: 
          - { label: "Orden", name: "order", widget: "number", default: 1 }

  - name: "branchOffices" 
    label: "Sucursales" 
    folder: "src/content/docs/branchOffices" 
    create: true 
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "navegacion"
        name: "sidebar"
        widget: "object"
        fields: 
          - { label: "Orden", name: "order", widget: "number", default: 1 }

  - name: "pointsOfSale" 
    label: "Puntos de Venta" 
    folder: "src/content/docs/pointsOfSale" 
    create: true 
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "navegacion"
        name: "sidebar"
        widget: "object"
        fields: 
          - { label: "Orden", name: "order", widget: "number", default: 1 }
  
  - name: "customers" 
    label: "Clientes" 
    folder: "src/content/docs/customers" 
    create: true 
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "navegacion"
        name: "sidebar"
        widget: "object"
        fields: 
          - { label: "Orden", name: "order", widget: "number", default: 1 }

  - name: "products" 
    label: "Productos" 
    folder: "src/content/docs/products" 
    create: true 
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "navegacion"
        name: "sidebar"
        widget: "object"
        fields: 
          - { label: "Orden", name: "order", widget: "number", default: 1 }

  - name: "rolesAndPermissions" 
    label: "Roles y Permisos" 
    folder: "src/content/docs/rolesAndPermissions" 
    create: true 
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "navegacion"
        name: "sidebar"
        widget: "object"
        fields: 
          - { label: "Orden", name: "order", widget: "number", default: 1 }