backend:
      name: git-gateway 
      branch: main
media_folder: "src/assets/images/uploads" # Location where files will be stored in the repo
collections:
  - name: "guides" # Used in routes, e.g., /admin/collections/blog
    label: "GUIAS" # Used in the UI
    folder: "src/content/docs/guides" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "hidden" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
    